[package]
name = "pcli2-batch-uploader"
version = "0.2.0"
edition = "2024"
description = "A batch uploader CLI for Physna pcli2"
repository = "https://github.com/jchultarsky101/pcli2-batch-uploader"
authors = ["Julian Chultarsky <jchultarsky@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["physna", "pcli2", "batch", "uploader", "cli"]
categories = ["command-line-utilities"]

[dependencies]
calamine = "0.26"
clap = { version = "4", features = ["derive"] }
console = "0.15"
indicatif = "0.17"
tempfile = "3"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zip = "2"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
simple_excel_writer = "0.2"
tempfile = "3"
zip = "2"

[package.metadata.wix]
upgrade-guid = "9FFAE864-36C3-474C-8CDA-F4819DD72E86"
path-guid = "FE111934-CDD4-4288-85EE-CE504C20C48B"
license = false
eula = false

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
