[package]
name = "pcli2-batch-uploader"
version = "0.1.0"
edition = "2024"
description = "A batch uploader CLI for Physna pcli2"
repository = "https://github.com/jchultarsky101/pcli2-batch-uploader"
license = "MIT"
readme = "README.md"
keywords = ["physna", "pcli2", "batch", "uploader", "cli"]
categories = ["command-line-utilities"]

[dependencies]
calamine = "0.26"
clap = { version = "4", features = ["derive"] }
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zip = "2"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
simple_excel_writer = "0.2"
tempfile = "3"
zip = "2"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
